//-----------------------------------------------------------------//
//	SCRIPT:	environmentPaths.mel
//	AUTHOR:	Jason Parks
//
//	START DATE:	June 20, 2012	
//
// 	DESCRIPTION: wrapper for python code
//
//-----------------------------------------------------------------//


// calls command from compiled python script
global proc environmentPaths(){
    python("import core.mayaCore");
    python("reload (core.mayaCore)");
    python("core.mayaCore.Maya().getEnv()");
}
